/*
 * Garage Door Status API
 *
 * API for updating and monitoring garage door status
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */
use std::fmt;
use std::fmt::Formatter;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GarageDoorStatus {
    /// Current status of the garage door
    #[serde(rename = "status")]
    pub status: Status,
}

impl GarageDoorStatus {
    pub fn new(status: Status) -> GarageDoorStatus {
        GarageDoorStatus {
            status,
        }
    }
}
/// Current status of the garage door
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "OPEN")]
    Open,
    #[serde(rename = "CLOSED")]
    Closed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Open
    }
}

impl fmt::Display for Status {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let s = match self {
            Status::Open => "OPEN",
            Status::Closed => "CLOSED",
        };
        write!(f, "{}", s)
    }
}
