/*
 * Garage Door Status API
 *
 * API for updating and monitoring garage door status
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    /// Error message describing what went wrong
    #[serde(rename = "message")]
    pub message: String,
}

impl Error {
    pub fn new(message: String) -> Error {
        Error {
            message,
        }
    }
}

